name: Run Soul Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *'

jobs:
  run_soul_workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: binary by @soulcracks
        run: chmod +x soulcracks
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install required packages
        run: |
          pip install telebot pymongo aiohttp

      - name: Run soul.py
        run: python3 soul.py
        
